apiVersion: batch/v1
kind: Job
metadata:
  name: wasm-filter-tile-0
spec:
  template:
    spec:
      runtimeClassName: wasmedge
      restartPolicy: Never
      containers:
        - name: wasm-tile-processor
          image: "none"  # dummy image, mandatory field
          command: ["/filter.wasm"]
          workingDir: /
          volumeMounts:
            - name: wasm-binary
              mountPath: /filter.wasm
              subPath: filter.wasm
              readOnly: true
      volumes:
        - name: wasm-binary
          hostPath:
            path: /Users/ghost/wasm-image-pipeline/shared/filter.wasm
            type: File
