apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
          - server
          - /data
          - --console-address
          - ":9001"
        env:
          - name: MINIO_ACCESS_KEY
            value: "minioadmin"
          - name: MINIO_SECRET_KEY
            value: "minioadmin"
        ports:
          - name: api
            containerPort: 9000
          - name: console
            containerPort: 9001
        volumeMounts:
          - mountPath: /data
            name: minio-data
      volumes:
        - name: minio-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: minio
  ports:
    - name: console
      port: 9001
      targetPort: 9001
