name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-wasip1

    - name: Install WasmEdge
      run: |
        curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash -s -- --version 0.13.5
        echo "$HOME/.wasmedge/bin" >> $GITHUB_PATH

    - name: Check formatting
      run: cargo fmt --check

    - name: Build filter module for wasm32-wasip1 in release mode
      run: |
        pushd modules/filter
        cargo build --target wasm32-wasip1 --release
        popd

    - name: Run cargo tests for filter module
      run: |
        pushd modules/filter
        cargo test
        popd

    - name: Test greyscale functionality using WasmEdge runtime
      run: |
        pushd modules/filter
        wasmedge target/wasm32-wasip1/release/filter.wasm process_stdin < test_assets/input.png > test_assets/output.png 2> debug.log
        popd